### ISSUE TITLE
job stay in OBIT on mom

### ISSUE THREAD

**Issue by stdweird** [adaptivecomputing/torque#343] opened 2015-12-02 07:53 UTC
We observed the following with 5.1-dev

* submit jobs, let them start on nodes
* stop pbs_server on master 
* let jobs finish with pbs_server still down
* wait a bit longer
* on the nodes momctl -d0 show jobs in OBIT
* start pbs_server
* job stay in OBIT on mom, and do not get cleaned up (we didn't wait that long, but certainly 10 minutes or so)

We expected that the OBIT states get cleared by itself, is this supposed to happen?
(for now this can be fixed with restart of pbs_mom.)

If the states should clear by them self, we'd like to know the expected timing (or what setting crontrols the retries/timeout/waiting...)

**Comment by knielson** [comment] 2015-12-02 16:19
Stijn,

I would think that these obits should clear themselves out when pbs_server
is restarted. We will try to reproduce the issue here.

Thanks

Ken

On Wed, Dec 2, 2015 at 12:53 AM, Stijn De Weirdt <notifications@github.com>
wrote:

> We observed the following with 5.1-dev
>
>    - submit jobs, let them start on nodes
>    - stop pbs_server on master
>    - let jobs finish with pbs_server still down
>    - wait a bit longer
>    - on the nodes momctl -d0 show jobs in OBIT
>    - start pbs_server
>    - job stay in OBIT on mom, and do not get cleaned up (we didn't wait
>    that long, but certainly 10 minutes or so)
>
> We expected that the OBIT states get cleared by itself, is this supposed
> to happen?
> (for now this can be fixed with restart of pbs_mom.)
>
> If the states should clear by them self, we'd like to know the expected
> timing (or what setting crontrols the retries/timeout/waiting...)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adaptivecomputing/torque/issues/343>.
>



-- 
[image: Adaptive Computing] <http://www.adaptivecomputing.com>
[image: Twitter] <http://twitter.com/AdaptiveMoab> [image: LinkedIn]
<http://www.linkedin.com/company/448673?goback=.fcs_GLHD_adaptive+computing_false_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2&trk=ncsrch_hits>
[image:
YouTube] <http://www.youtube.com/adaptivecomputing> [image: GooglePlus]
<https://plus.google.com/u/0/102155039310685515037/posts> [image: Facebook]
<http://www.facebook.com/pages/Adaptive-Computing/314449798572695?fref=ts>
[image:
RSS] <http://www.adaptivecomputing.com/feed>
Ken Nielson Sr. Software Engineer
+1 801.717.3700 office    +1 801.717.3738 fax
1712 S. East Bay Blvd, Suite 300     Provo, UT 84606
www.adaptivecomputing.com

**Comment by itkovian** [comment] 2016-03-09 10:45
Hi @knielson, were you able to reproduce this behaviour?

**Comment by knielson** [comment] 2016-03-09 15:21
Andy,

Not yet. But I will try it now.

Ken

On Wed, Mar 9, 2016 at 3:45 AM, Andy Georges <notifications@github.com>
wrote:

> Hi @knielson <https://github.com/knielson>, were you able to reproduce
> this behaviour?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adaptivecomputing/torque/issues/343#issuecomment-194236280>
> .
>



-- 
[image: Adaptive Computing] <http://www.adaptivecomputing.com>
[image: Twitter] <http://twitter.com/AdaptiveMoab> [image: LinkedIn]
<http://www.linkedin.com/company/448673?goback=.fcs_GLHD_adaptive+computing_false_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2&trk=ncsrch_hits>
[image:
YouTube] <http://www.youtube.com/adaptivecomputing> [image: GooglePlus]
<https://plus.google.com/u/0/102155039310685515037/posts> [image: Facebook]
<http://www.facebook.com/pages/Adaptive-Computing/314449798572695?fref=ts>
[image:
RSS] <http://www.adaptivecomputing.com/feed>
Ken Nielson Sr. Software Engineer
+1 801.717.3700 office    +1 801.717.3738 fax
1712 S. East Bay Blvd, Suite 300     Provo, UT 84606
www.adaptivecomputing.com

**Comment by knielson** [comment] 2016-03-09 15:42
Andy,

I just tried this with 6.0.1 and the job completes. I will now try with
5.1.2.

Ken

On Wed, Mar 9, 2016 at 3:45 AM, Andy Georges <notifications@github.com>
wrote:

> Hi @knielson <https://github.com/knielson>, were you able to reproduce
> this behaviour?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adaptivecomputing/torque/issues/343#issuecomment-194236280>
> .
>



-- 
[image: Adaptive Computing] <http://www.adaptivecomputing.com>
[image: Twitter] <http://twitter.com/AdaptiveMoab> [image: LinkedIn]
<http://www.linkedin.com/company/448673?goback=.fcs_GLHD_adaptive+computing_false_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2&trk=ncsrch_hits>
[image:
YouTube] <http://www.youtube.com/adaptivecomputing> [image: GooglePlus]
<https://plus.google.com/u/0/102155039310685515037/posts> [image: Facebook]
<http://www.facebook.com/pages/Adaptive-Computing/314449798572695?fref=ts>
[image:
RSS] <http://www.adaptivecomputing.com/feed>
Ken Nielson Sr. Software Engineer
+1 801.717.3700 office    +1 801.717.3738 fax
1712 S. East Bay Blvd, Suite 300     Provo, UT 84606
www.adaptivecomputing.com

**Comment by knielson** [comment] 2016-03-09 16:34
I reproduced the problem with 5.1.2. I will next see if it has been fixed
in 5.1-dev.



On Wed, Mar 9, 2016 at 8:42 AM, Ken Nielson <knielson@adaptivecomputing.com>
wrote:

> Andy,
>
> I just tried this with 6.0.1 and the job completes. I will now try with
> 5.1.2.
>
> Ken
>
> On Wed, Mar 9, 2016 at 3:45 AM, Andy Georges <notifications@github.com>
> wrote:
>
>> Hi @knielson <https://github.com/knielson>, were you able to reproduce
>> this behaviour?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/adaptivecomputing/torque/issues/343#issuecomment-194236280>
>> .
>>
>
>
>
> --
> [image: Adaptive Computing] <http://www.adaptivecomputing.com>
> [image: Twitter] <http://twitter.com/AdaptiveMoab> [image: LinkedIn]
> <http://www.linkedin.com/company/448673?goback=.fcs_GLHD_adaptive+computing_false_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2&trk=ncsrch_hits> [image:
> YouTube] <http://www.youtube.com/adaptivecomputing> [image: GooglePlus]
> <https://plus.google.com/u/0/102155039310685515037/posts> [image:
> Facebook]
> <http://www.facebook.com/pages/Adaptive-Computing/314449798572695?fref=ts> [image:
> RSS] <http://www.adaptivecomputing.com/feed>
> Ken Nielson Sr. Software Engineer
> +1 801.717.3700 office    +1 801.717.3738 fax
> 1712 S. East Bay Blvd, Suite 300     Provo, UT 84606
> www.adaptivecomputing.com
>



-- 
[image: Adaptive Computing] <http://www.adaptivecomputing.com>
[image: Twitter] <http://twitter.com/AdaptiveMoab> [image: LinkedIn]
<http://www.linkedin.com/company/448673?goback=.fcs_GLHD_adaptive+computing_false_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2&trk=ncsrch_hits>
[image:
YouTube] <http://www.youtube.com/adaptivecomputing> [image: GooglePlus]
<https://plus.google.com/u/0/102155039310685515037/posts> [image: Facebook]
<http://www.facebook.com/pages/Adaptive-Computing/314449798572695?fref=ts>
[image:
RSS] <http://www.adaptivecomputing.com/feed>
Ken Nielson Sr. Software Engineer
+1 801.717.3700 office    +1 801.717.3738 fax
1712 S. East Bay Blvd, Suite 300     Provo, UT 84606
www.adaptivecomputing.com

**Comment by knielson** [comment] 2016-03-09 17:03
So this is fixed in 5.1-dev as well. It looks like the commits which fixed
the problem are 171e3dd69efee1e90ea9c059e78baff97079c12
and  03cb65b32492eee2edb8504125d94fedfc22fc09 which went in on Feb. 18,
2016.

Ken


On Wed, Mar 9, 2016 at 9:34 AM, Ken Nielson <knielson@adaptivecomputing.com>
wrote:

> I reproduced the problem with 5.1.2. I will next see if it has been fixed
> in 5.1-dev.
>
>
>
> On Wed, Mar 9, 2016 at 8:42 AM, Ken Nielson <
> knielson@adaptivecomputing.com> wrote:
>
>> Andy,
>>
>> I just tried this with 6.0.1 and the job completes. I will now try with
>> 5.1.2.
>>
>> Ken
>>
>> On Wed, Mar 9, 2016 at 3:45 AM, Andy Georges <notifications@github.com>
>> wrote:
>>
>>> Hi @knielson <https://github.com/knielson>, were you able to reproduce
>>> this behaviour?
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/adaptivecomputing/torque/issues/343#issuecomment-194236280>
>>> .
>>>
>>
>>
>>
>> --
>> [image: Adaptive Computing] <http://www.adaptivecomputing.com>
>> [image: Twitter] <http://twitter.com/AdaptiveMoab> [image: LinkedIn]
>> <http://www.linkedin.com/company/448673?goback=.fcs_GLHD_adaptive+computing_false_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2&trk=ncsrch_hits> [image:
>> YouTube] <http://www.youtube.com/adaptivecomputing> [image: GooglePlus]
>> <https://plus.google.com/u/0/102155039310685515037/posts> [image:
>> Facebook]
>> <http://www.facebook.com/pages/Adaptive-Computing/314449798572695?fref=ts> [image:
>> RSS] <http://www.adaptivecomputing.com/feed>
>> Ken Nielson Sr. Software Engineer
>> +1 801.717.3700 office    +1 801.717.3738 fax
>> 1712 S. East Bay Blvd, Suite 300     Provo, UT 84606
>> www.adaptivecomputing.com
>>
>
>
>
> --
> [image: Adaptive Computing] <http://www.adaptivecomputing.com>
> [image: Twitter] <http://twitter.com/AdaptiveMoab> [image: LinkedIn]
> <http://www.linkedin.com/company/448673?goback=.fcs_GLHD_adaptive+computing_false_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2&trk=ncsrch_hits> [image:
> YouTube] <http://www.youtube.com/adaptivecomputing> [image: GooglePlus]
> <https://plus.google.com/u/0/102155039310685515037/posts> [image:
> Facebook]
> <http://www.facebook.com/pages/Adaptive-Computing/314449798572695?fref=ts> [image:
> RSS] <http://www.adaptivecomputing.com/feed>
> Ken Nielson Sr. Software Engineer
> +1 801.717.3700 office    +1 801.717.3738 fax
> 1712 S. East Bay Blvd, Suite 300     Provo, UT 84606
> www.adaptivecomputing.com
>



-- 
[image: Adaptive Computing] <http://www.adaptivecomputing.com>
[image: Twitter] <http://twitter.com/AdaptiveMoab> [image: LinkedIn]
<http://www.linkedin.com/company/448673?goback=.fcs_GLHD_adaptive+computing_false_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2&trk=ncsrch_hits>
[image:
YouTube] <http://www.youtube.com/adaptivecomputing> [image: GooglePlus]
<https://plus.google.com/u/0/102155039310685515037/posts> [image: Facebook]
<http://www.facebook.com/pages/Adaptive-Computing/314449798572695?fref=ts>
[image:
RSS] <http://www.adaptivecomputing.com/feed>
Ken Nielson Sr. Software Engineer
+1 801.717.3700 office    +1 801.717.3738 fax
1712 S. East Bay Blvd, Suite 300     Provo, UT 84606
www.adaptivecomputing.com

**Comment by itkovian** [comment] 2016-05-11 11:48
OK, I've tested this with 5.1-dev (commit da68435)  and 6.0-dev (commit 933409e) and it seems to work fine now.

**Comment by knielson** [comment] 2016-05-11 15:11
Thank you for confirming the fix.

**Closed by knielson** 2016-05-11 15:11 UTC
